config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: :delete
  resources :categories, except: :destroy
  resources :products, except: :destroy
  resources :orders, except: :destroy
  resources :line_items, only: %i[create destroy update]
  resources :wish_lists
  resources :wish_list_items, only: %i[create destroy]
  resources :reviews
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :wish_lists
  has_many :reviews
  has_many :orders
  has_many :line_items, through: :orders
  has_one :drafted_order, -> { drafted }, class_name: 'Order'
  has_many :completed_orders, -> { completed }, class_name: 'Order'
  has_one :address, as: :addressable
  accepts_nested_attributes_for :address
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Authorizable

  def show
    @user = User.find(params[:id])
    @drafted_order = current_user.drafted_order
    @completed_orders = current_user.completed_orders
  end

  def edit
    @user = User.find(params[:id])
    @user.build_address if @user.address.blank?
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      sign_in(@user, bypass: true)
      redirect_to edit_user_path(@user), notice: 'Settings have been succesfully updated'
    else
      redirect_to edit_user_path(@user), notice: 'Not able to update settings'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email, :password, :password_confirmation,
      address_attributes: %i[id building_address post_index number]
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_addresses_fields.slim
div = f.label :number, 'Number*'
div = f.text_field :number
div = f.label :post_index, 'Post index*'
div = f.text_field :post_index
div = f.label :building_address, 'Building address*'
div = f.text_field :building_address

app/views/users/edit.slim
div
  = form_for @user do |form|
    div = form.label :email
    div = form.text_field :email, readonly: true
    = form.fields_for :address do |addr_form|
      = render 'addresses_fields', f: addr_form
    div = form.submit 'Update address'
    hr
    div Change password
  = form_for @user do |pass_form|
    div = pass_form.password_field :password
    div = pass_form.password_field :password_confirmation
    div = pass_form.submit 'Update password'

  - if flash.notice
    div class='notice' = flash.notice

app/views/users/show.slim
h1 = @user.email
div = link_to 'Settings', edit_user_path

div = @wish_lists.present? ? (link_to 'Your wish lists', wish_lists_path) : (link_to "Make a new wish list", new_wish_list_path)

div = @drafted_order ? (link_to 'Shopping cart', edit_order_path(current_user.drafted_order.id)) : 'Shopping cart is blank'
div = @completed_orders.present? ? (link_to 'Orders', orders_path) : 'You have no orders yet'
div = link_to 'Wish lists', wish_lists_path
div = link_to 'Back', root_path