config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: :delete
  resources :categories, except: :destroy
  resources :products, except: :destroy
  resources :orders, except: :destroy
  resources :line_items, only: %i[create destroy update]
  resources :wish_lists
  resources :wish_list_items, only: %i[create destroy]
  resources :reviews
  root 'home#index'
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: %i[drafted completed archived]

  belongs_to :user

  has_many :line_items
  has_many :products, through: :line_items

  has_one :address, as: :addressable

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :line_items

  delegate :post_index, :number, :building_address, to: :address, prefix: false, allow_nil: true
  after_touch :update_total
  before_update :update_product_quantity, if: %i[will_save_change_to_status? completed?]

  private

  def update_product_quantity
    line_items.each do |li|
      li.product.update(quantity: li.product.quantity - li.quantity)
    end
  end

  def update_total
    update(total: line_items.sum(:subtotal))
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include Authorizable

  def index
    @completed_orders = current_user.completed_orders
    @products = Product.all
  end

  def show
    @order = Order.find(params[:id])
    @line_items = @order.line_items
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to orders_path(@order)
    else
      render 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
    @line_items = @order.line_items
    @order.build_address if @order.address.blank?
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to orders_path
    else
      render 'edit', notice: 'You must fill the fields with an asterisk'
    end
  end

  def destroy
    @order = order.find(params[:id])
    if @order.destroy
      redirect_to orders_path
    else
      render 'show'
    end
  end

  private

  def order_params
    params.require(:order).permit(
      :user_id, :note, :status,
      line_items_attributes: %i[quantity id],
      address_attributes: %i[id building_address post_index number]
    )
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_completed_order.slim
li = link_to "Order:# #{completed_order.id}", order_path(completed_order.id)

app/views/orders/_edit_order.slim
  = form_for order do |form|
    ol
      = form.fields_for :line_items do |li_form|
        = render 'product_line', form: li_form
    = form.hidden_field :status, value: :completed
    = form.hidden_field :user_id
    = form.fields_for :address do |addr_form|
      = render 'users/addresses_fields', f: addr_form
    div = form.label :note
    div = form.text_area :note
    div = form.submit 'Create order'

app/views/orders/_line_item.slim
li
  div
    | Product name:
    =< link_to line_item.product_name, product_path(line_item.product)
  div
    | Quanitity:
    =< line_item.quantity
  div
    | Product price:
    =< number_to_currency(line_item.product_price, precision: 0)
  div
    | Subtotal:
    =< number_to_currency(line_item.subtotal, precision: 0)

app/views/orders/_product_line.slim
li
  div
  => link_to form.object.product_name, product_path(form.object.product_id)
  | |
  =< link_to 'Delete', line_item_path(form.object.id), method: :delete, data: { confirm: 'Normalno?' }
  div
  | Quantity:
  => form.number_field :quantity, min: 1, max: form.object.product.quantity
  div
  | Subtotal:
  =< number_to_currency(form.object.subtotal, precision: 0)

app/views/orders/edit.slim
div = link_to @order.user.email, user_path(@order.user)
br
div
  | Total:
  =< number_to_currency(@order.total, precision: 0)
div
= @order.line_items.present? ? render('edit_order', order: @order) : 'There are no items yet.'
- if flash.notice
  div class='notice' = flash.notice
= link_to 'Browse', root_path

app/views/orders/index.slim
div
  =<link_to current_user.email, user_path(current_user.id)
div
  |Your orders:
  ul = render partial: 'completed_order', collection: @completed_orders

app/views/orders/show.slim
div
  = link_to @order.user.email, user_path(@order.user.id)
  |'s orders
div Order details:
div
  | Status:
  =< @order.status

div
  | Total:
  =< number_to_currency(@order.total, precision: 0)
ol
  div = render partial: 'line_item', collection: @line_items
br
div Adress
div
  | Post index:
  =< @order.post_index
div
  | Number:
  =< @order.number
div
  |Building:
  =< @order.building_address
div
  | Note:
  =< @order.note
div = link_to 'Go to orders', orders_path