config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: :delete
  resources :categories, except: :destroy
  resources :products, except: :destroy
  resources :orders, except: :destroy
  resources :line_items, only: %i[create destroy update]
  resources :wish_lists
  resources :wish_list_items, only: %i[create destroy]
  resources :reviews
  root 'home#index'
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :products, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include Authorizable

  def show
    @category = Category.friendly.find(params[:id])
    @products = current_user.admin? ? Product.all.order(:status) : Product.not_archived.order(:status)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path
    else
      render 'home/index'
    end
  end

  def edit
    @category = Category.friendly.find(params[:id])
  end

  def update
    @category = Category.friendly.find(params[:id])
    if @category.update(category_params)
      redirect_to root_path
    else
      render 'home/index'
    end

  end

  def destroy
    @category = Category.friendly.find(params[:id])
    if @category.destroy
      redirect_to root_path
    else
      render 'home/index'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.slim
li = link_to category.name, category_path(category)

app/views/categories/_category_new.slim
option = category.name

app/views/categories/new.slim
= form_for @category do |form|
  div
    = form.label :name
  br
    = form.text_field :name
  br
    = form.submit
= link_to 'Main page', root_path

app/views/categories/show.slim
div
  h1 = @category.name
  = link_to 'Add products', new_product_path(category_id: @category.id)
  br
  = link_to 'Main page', root_path
  br
  = link_to 'Destroy', category_path, method: :delete, data: { confirm: 'Noramalniy? ' }
br
h1 Products
- if @category.products.blank?
  div There are no products yet
- else
  ul
    = render @products