config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: :delete
  resources :categories, except: :destroy
  resources :products, except: :destroy
  resources :orders, except: :destroy
  resources :line_items, only: %i[create destroy update]
  resources :wish_lists
  resources :wish_list_items, only: %i[create destroy]
  resources :reviews
  root 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
  enum status: %i[in_stock out_of_stock archived]

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :wish_list_items
  has_many :wish_lists, through: :wish_list_items

  has_many :reviews
  has_many :top_rated, -> { where('rating >= ?', 4) }, class_name: 'Review'
  has_many :line_items
  has_many :orders, through: :line_items

  has_one_attached :main_image
  has_many_attached :images
  validates_size_of :images, maximum: 5

  belongs_to :category

  validates :name, uniqueness: true
  after_touch :update_rating
  before_save :assign_in_stock, if: -> { will_save_change_to_quantity? && !archived? }
  before_save :deplete_quantity, if: %i[will_save_change_to_status? archived?]
  before_save :update_slug, if: :will_save_change_to_name?

  private

  def update_slug
    self.slug = name
  end

  def deplete_quantity
    self.quantity = 0
  end

  def update_rating
    update(average_rating: reviews.sum(:rating) / reviews.size.to_f)
  end

  def assign_in_stock
    self.status = quantity.positive? ? :in_stock : :out_of_stock
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Authorizable

  def index
    @pagy, @products = pagy(current_user.admin? ? Product.all.order(:status) : Product.not_archived.order(:status), items: 9)
  end

  def show
    @product = Product.friendly.find(params[:id])
    @wish_lists = WishList.all
    @wish_list_item = WishListItem.new(product_id: @product.id)
    @line_item = current_user.drafted_order&.line_items&.find_by(product_id: @product.id) || LineItem.new(product_id: @product.id)
    @review = Review.new(product_id: @product.id, user_id: current_user.id)
    @reviews = @product.reviews
    @bought_product = current_user.line_items.find_by(product_id: @product.id, orders: { status: :completed })
  end

  def new
    @product = Product.new
    @category = Category.find(params[:category_id])
  end

  def create
    @product = Product.new(product_params)
    @category = @product.category
    if @product.save
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def edit
    @product = Product.friendly.find(params[:id])
  end

  def update
    @product = Product.friendly.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.friendly.find(params[:id])
    if @product.destroy
      redirect_to products_path, notice: "#{@product.name} has been successfully deleted."
    else
      flash[:notice] = 'Ooops. Something went wrong. Try later'
      render 'show'
    end
  end

  private

  def product_params
    params.require(:product).permit(:status, :quantity, :name, :price, :category_id, :main_image, images: [])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_line_item_form.slim
= form_for @line_item do |form|
  = form.hidden_field :product_id
  div
    |Number of items
    =< form.number_field :quantity, min: 1, max: @product.quantity
  = form.submit 'Add product to a shopping cart'

app/views/products/_product.slim
li
  => link_to product.name, product_path(product)
  ||
  =< product.status.titleize

app/views/products/_review_form.slim
= form_for @review do |form|
  = form.hidden_field :user_id
  = form.hidden_field :product_id
  div = form.text_area :body, placeholder: 'Your review...'
  div = form.label :rating, 'Your rating'
  div = form.number_field :rating, min: 0, max: 5
  div = form.submit 'Leave a review'

app/views/products/edit.slim
= form_for @product do |form|
  div = form.label :quantity
  div = form.number_field :quantity

  div = form.label :name
  div = form.text_field :name

  div = form.number_field :price
  div = form.label :price

  div = form.label :status
  div = form.select :status, (Product.statuses.map { |k, _| [k.titleize, k] })
  = form.submit 'Update product fields'

app/views/products/index.slim
h1 Products
ul = render @products

== pagy_nav(@pagy)

app/views/products/new.slim
h1
  | Add product to category:
  =<  @category.name
= form_for @product do |form|
  div = form.hidden_field :category_id, value: @category.id
  div = form.file_field :images, multiple: true
  div = form.label :name
  div = form.text_field :name
  div = form.label :price
  div = form.number_field :price
  div = form.label :quantity
  div = form.number_field :quantity
  div = form.submit

app/views/products/show.slim
- if flash.notice
    .notice_div = flash.notice
h2
  | Category:
  =< link_to @product.category.name, category_path(@product.category_id)
div
  => @product.name
  - if current_user.admin?
    | |
    =< link_to 'Archive product', product_path(@product, product: { status: :archived }), method: :patch, data: { confirm: 'Are you sure about that?' } if current_user.admin?
    | |
    =< link_to 'Edit', edit_product_path(@product)
div = image_tag(@product.main_image, size = '500x400') if @product.main_image.attached?
- @product.images.each do |image|
    div = image_tag(image, size: '100x50')

div
  | Price:
  =< number_to_currency(@product.price.to_i, precision: 0)
div
  | Rating:
  =< number_with_precision(@product.average_rating.to_f, precision: 1)
  | /5
div = current_user.wish_lists.present? ? render('wish_list_items/form') : "You don't have any wish lists yet!"

div = link_to 'Create a new wishlist', new_wish_list_path(product_id: @product.id)

- if @product.in_stock?
  div Product is in stock
  div = render 'line_item_form'
  div = link_to 'shopping cart', edit_order_path(current_user.drafted_order) if current_user.drafted_order
- else
  div Product is out of stock

h1 Buyers' reviews
- if @bought_product
  = render 'review_form'
= render @reviews